global:
  hazelcast: hazelcast:5701
  replicas: 1
  port: 9000

service:
  type: ClusterIP
  port: 9000

image:
  repository: camunda/zeeqs
  tag: latest

resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
